### PR TITLE
Feature: Logging with Grafana, Loki and Promtail

### PR DESCRIPTION
**Pull request by shei99**

### CODE REVIEW

**Review by D4ykoo — COMMENTED** [review]
lgtm!

wait for another approve since one commit is a force push
@shei99

**Comment by shei99** [comment]
Please add the Ansible configuration for the Keycloak client and client scope.

**Comment by shei99** [comment]
Maybe move the values.yml from Loki and Promtail in the grafana folder?

**Review by D4ykoo — APPROVED** [review]
Done

**Pull request merged**
